version: '3.8'

services:
  goaldsl:
    image: rbml
    command: uvicorn rosbridgeml.api:api --host 0.0.0.0 --port 8080 --root-path ${ROOT_PATH:-/}
    ports:
      - ${PORT:-8080}:8080
    environment:
      - API_KEY=${API_KEY}
